server:
  port: 8889
  
spring:
  application:
    name: cliente-api
  data:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgresql
    url: jdbc:postgresql://challenge.cckzrxnktkrr.sa-east-1.rds.amazonaws.com/postgres
    username: postgres
    password: challengedev040990
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    properties:
      format-sql: true
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress:true
