server:
  port: 8888
 
spring:
   application:
    name: auth-api

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
     preferIpAddress:true 

